name: common_github_app
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  bloc: ^8.1.2
  equatable: ^2.0.5
  freezed_annotation: ^2.4.1
  http: ^1.1.0
  json_annotation: ^4.8.1
  stream_transform: ^2.1.0
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  lints: ^2.1.1
  test: ^1.24.6
